---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.0.1"
license_file: LICENSE
name: vyos
description: Ansible Network Collection for VYOS devices.
namespace: vyos
readme: README.md
repository: https://github.com/ansible-collections/vyos.vyos
tags: [vyos, networking]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
