---
name: Test collection

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
  sanity:
    uses: Qalthos/github_actions/.github/workflows/sanity.yml@milestone-no-fail
    with:
      matrix_include: >-
        [
          {
            "os": "ubuntu-20.04",
            "ansible-version": "stable-2.9",
            "python-version": "3.6",
            "unstable": false,
          },
          {
            "os": "ubuntu-latest",
            "ansible-version": "stable-2.15",
            "python-version": "3.10",
            "unstable": true,
          },
          {
            "os": "ubuntu-latest",
            "ansible-version": "milestone",
            "python-version": "3.10",
            "unstable": true,
          },
          {
            "os": "ubuntu-latest",
            "ansible-version": "devel",
            "python-version": "3.10",
            "unstable": true,
          },
        ]
  unit-galaxy:
    uses: ansible-network/github_actions/.github/workflows/unit_galaxy.yml@main
  unit-source:
    uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main
    with:
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git
  all_green:
    if: ${{ always() }}
    needs:
      - changelog
      - sanity
      - unit-galaxy
      - unit-source
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.changelog.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}',
          '${{ needs.unit-source.result }}'
          ]) == {'success'}"
